name: flutter_audio_player
description: Plugin that allow flutter to play local audio simple by a list.
version: 0.1.1
author: Bai <equweiyu@hotmail.com>
homepage: https://github.com/hui-z/audio_player

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.example.audioplayer
    pluginClass: AudioPlayerPlugin